### ISSUE TITLE
Implement the reward system in the tracker 

### ISSUE THREAD

**Issue by annieliu10** [kaiyyang/cpsc416_GroupProject_ReliableBT#4]
1. pingTimer to ping every once so often to see which peer has the greatest 
2. Prioritize whichever peer has the greatest uploads

**Comment by Maxwell-Yang-2001** [comment]
As of the current implementatioin, we only implement a punishment model for bad actor, but anyone who is not a bad actor will get access to a random baseline provider if one exists, as we don't have a rank on the quality of different baseline providers. Closing the issue.
