### ISSUE TITLE
Calculate Download and Upload Speed of each Peer in the Tracker 

### ISSUE THREAD

**Issue by annieliu10** [kaiyyang/cpsc416_GroupProject_ReliableBT#6]
- peer reports to the tracker how much they've downloaded/uploaded during each ping so we can calculate the speed using the amount of upload/download and the time interval

**Comment by Maxwell-Yang-2001** [comment]
As we didn't end up doing sophiscated bad actor identification (currently bad actor is identified by a peer that downloads with zero uploaded bytes since last announce, despite having more than a set amount of leechers to upload to), this is not a utility in our implementation. Closing the issue.
